services:
  database:
    image: postgres:15-alpine
    container_name: video-processor-database
    environment:
      POSTGRES_DB: fiap_videos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - video-processor-network

  minio:
    image: minio/minio:latest
    container_name: video-processor-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - video-processor-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: video-processor-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - video-processor-network

  redis:
    image: redis:7-alpine
    container_name: video-processor-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - video-processor-network

  api:
    image: henriquemh/video-processor-api:latest
    container_name: video-processor-api
    ports:
      - "8000:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: fiap_videos
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - video-processor-network

  upload-service:
    build: ./src
    container_name: video-processor-core
    ports:
      - "8081:8081"
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: videos
      MINIO_USE_SSL: false
      API_BASE_URL: http://api:8080
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_URL: redis://redis:6379
      SERVER_PORT: 8081
    depends_on:
      minio:
        condition: service_healthy
      api:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - video-processor-network

  frontend:
    image: henriquemh/video-processor-frontend:latest
    container_name: video-processor-frontend
    environment:
      API_BASE_URL: http://localhost:8000
      UPLOAD_BASE_URL: http://localhost:8081
    ports:
      - "80:80"
    depends_on:
      - api
      - upload-service
    networks:
      - video-processor-network

volumes:
  minio_data:
  pgdata:
  rabbitmq_data:
  redis_data:

networks:
  video-processor-network:
    name: video-processor-network
    driver: bridge